name: Dockerize

on:
  push:
    branches:
      - master

jobs:
  dockerize:
    runs-on: ubuntu-18.04

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install npm packages
        run: npm install

      - name: Transpile typescript
        run: npm run build

      - name: Dockerize and push to registry
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: $PASSWORD
          image-name: devlog-backend
