name: Dockerize

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dockerize:
    runs-on: ubuntu-18.04

    env:
      NODE_ENV: development

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install npm packages
        run: npm install

      - name: Transpile typescript
        run: npm run build

      - name: Dockerize and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
          repository: acrylicshrimp/devlog-backend
          tags: latest
